### ISSUE TITLE
Doesn't compile on fusetools 0.28

### ISSUE THREAD

**Issue by josemanuelp** [bolav/fuse-sqlite#12]
-compile:
    [javac] Compiling 109 source files to ..../app/src/main/bin/classes
    [javac] warning: [options] source value 1.5 is obsolete and will be removed in a future release
    [javac] warning: [options] target value 1.5 is obsolete and will be removed in a future release
    [javac] warning: [options] To suppress warnings about obsolete options, use -Xlint:-options.
    [javac] .../app/src/main/java/com/foreign/Bolav/ForeignHelpers/JSList.java:32: error: incompatible types: Object cannot be converted to UnoObject
    [javac]                             com.foreign.Bolav.ForeignHelpers.JSDict.FromJava277(ddict, obj);
    [javac]                                                                                 ^
    [javac] Note: Some input files use or override a deprecated API.
    [javac] Note: Recompile with -Xlint:deprecation for details.
    [javac] Note: Some messages have been simplified; recompile with -Xdiags:verbose to get full output
    [javac] 1 error
    [javac] 3 warnings

**Comment by josemanuelp** [comment]
Could compile it with a simple patch:

```
--- bolav/fuse-foreignhelpers/ListDict.uno.orig 2016-10-28 10:27:44.000000000 -0400
+++ bolav/fuse-foreignhelpers/ListDict.uno  2016-10-28 10:27:57.000000000 -0400
@@ -44,7 +44,7 @@
            java.util.List l = (java.util.List)ary;
            for (Object obj : l) {
                if (obj instanceof java.util.HashMap) {
-                   Object ddict = @{JSList:Of(_this).NewDictRow():Call()};
+                   UnoObject ddict = @{JSList:Of(_this).NewDictRow():Call()};
                    @{JSDict:Of(ddict).FromJava(Java.Object):Call(obj)};
                }
                else {
```

Don't know if it works yet...

**Comment by bolav** [comment]
Did it work? If so will you submit a PR?

**Comment by josemanuelp** [comment]
Yes it worked. 

PR submitted.

Thanks.
